blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.home, name="home"),
    path("post_detail/<slug:slug>", views.post_detail, name="post_detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),

    path("", include("blog.urls", namespace="blog")),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
    path("accounts/", include("users.urls", namespace="users")),
    ]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path

from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.index, name="index" ),
    path("create_post", views.create_post, name="create_post"),
    path("delete_post/<slug:slug>", views.delete_post, name="delete_post"),
    path("update_post/<slug:slug>", views.update_post, name="update_post"),
    path("edit_profile", views.edit_profile, name="edit_profile"),
]

dashboard/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    first_name = models.CharField(max_length=30, blank=True, null=True)
    last_name = models.CharField(max_length=30, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    state = models.CharField(max_length=100, blank=True, null=True)
    postal_code = models.CharField(max_length=20, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)
    image = models.ImageField("Profile image", default="default_profile.png",
                               null=True, blank=True, upload_to="uploads/users/profiles")
    publish_date = models.DateField(auto_now_add=True)

    created_at = models.DateTimeField(verbose_name="Created At", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="Updated At", auto_now=True)


    def __str__(self):
        return self.user.username

dashboard/forms.py
from django import forms

from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["first_name", "last_name", "address", "city", "state", "postal_code", "country", "image"]

dashboard/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone

from blog.forms import PostForm
from blog.models import Post

from .forms import ProfileForm

# Create your views here.


@login_required(login_url="/accounts/login")
def index(request):
    posts = Post.objects.filter(owner = request.user)
    return render(request, "dashboard/index.html", {"posts": posts})



@login_required(login_url="/accounts/login")
def create_post(request):
    if request.method == "POST":

        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.owner = request.user
            post.published_date = timezone.now()
            post.save()

            form.save_m2m()

            messages.success(request, "Post create successfully")
            return redirect("/")
    else:
        form = PostForm()
    return render(request, "dashboard/post_create.html", {"form": form})


@login_required(login_url="/accounts/login")
def delete_post(request, slug):
    post = get_object_or_404(Post, slug = slug)
    if request.method == "POST" and request.user == post.owner:
        messages.success(request, "the post deleted successfully")
        post.delete()
        return redirect("/dashboard")
    return render(request, "dashboard/post_delete.html", {"post": post})

@login_required(login_url="/accounts/login")
def update_post(request, slug):

    post = get_object_or_404(Post, slug = slug)
    if request.user == post.owner:
        if request.method == "POST":
            form = PostForm(request.POST, request.FILES, instance=post)
            if form.is_valid():
                form.save()
                messages.success(request, "the post updated successfully")
                return redirect("/dashboard")
    else:
        messages.warning(request, "this post is not yours for update" )
        return redirect("/dashboard")

    form = PostForm(instance=post)
    return render(request, "dashboard/update_post.html", {"form": form})





@login_required
def edit_profile(request):
    if request.method == "POST":
        form = ProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            messages.success(request, "Your profile update successfully")
            return redirect("dashboard:edit_profile")

    else:
        form = ProfileForm(instance=request.user.profile)

    return render(request, "dashboard/profile.html", {"form": form})

dashboard/templates/dashboard/index.html
{% extends 'dashboard_base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col">
            <h1 class="mb-4">Dashboard</h1>

            {% if posts %}
            <div class="mb-4">
                <a href="{% url 'dashboard:create_post' %}" class="btn btn-primary">
                    Create New Post
                </a>
            </div>
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <thead class="table">
                        <tr>
                            <th scope="col">Image</th>
                            <th scope="col">Title</th>
                            <th scope="col">Content</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for post in posts %}
                            <tr>
                                <td>
                                    <a href="{% url 'blog:post_detail' post.slug %}">
                                        <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-thumbnail" style="width: 150px; height: 100px;">
                                    </a>
                                </td>
                                <td>{{ post.title }}</td>
                                <td>{{ post.body|truncatewords:30 }}</td>
                                <td>
                                    <a href="{% url 'dashboard:update_post' post.slug %}" class="btn btn-warning btn-sm">Edit</a>
                                    <a href="{% url 'dashboard:delete_post' post.slug %}" class="btn btn-danger btn-sm">Delete</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% else %}
            <div class="alert" role="alert">
                No posts yet. <a href="{% url 'dashboard:create_post' %}">Create one</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/post_create.html
{% extends 'dashboard_base.html' %}

{% block title %}
    Create Post
{% endblock title %}
{% load crispy_forms_tags %}


{% block content %}
    
<h2>New post</h2>
<form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="save btn btn-secondary">Save</button>
</form>
{% endblock content %}

dashboard/templates/dashboard/post_delete.html
{% extends 'base.html' %}

{% block title %}
    Delete Post
{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title text-center">Do you really want to delete this post?</h3>
                    <hr>

                    <h5 class="text-danger">{{ post.title }}</h5>
                    <p>{{ post.body|truncatewords:30 }}</p>

                    <form action="{% url 'dashboard:delete_post' post.slug %}" method="post">
                        {% csrf_token %}
                        <div class="d-flex justify-content-between">
                            <a href="{% url 'blog:post_detail' post.slug %}" class="btn btn-secondary">Cancel</a>
                            <input type="submit" class="btn btn-danger" value="Delete">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

dashboard/templates/dashboard/profile.html
{% extends 'base.html' %}

{% block title %}Edit Profile{% endblock %}
{% load crispy_forms_tags %} 

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card">
                <div class="card-body">
                    <h2>Edit Profile</h2>

                    <form method="post">
                        {% csrf_token %}
                        {{form|crispy}}
                        <button type="submit" class="btn btn-primary">Save Changes</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/update_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
    update post
{% endblock title %}


{% block content %}
<h2>Update post</h2>
<form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy}}
    <button type="submit" class="save btn btn-secondary">Save</button>
</form>
{% endblock content %}